version: '3.8'
services:
    redis:
        image: redis:alpine
        ports:
            - '6379:6379'
        expose:
            - '6379'
    postgres:
        image: postgres:alpine
        env_file:
            - ./messager-service/.env
        volumes:
            - ./postgres:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        expose:
            - '5432'
    messager-service:
        build: ./messager-service
        image: messager
        ports:
            - '8080:8080'
        expose:
            - '8080'
        environment:
            - ENV=dev
        volumes:
            - ./messager-service:/src/messager
        command: reflex -r "\.go$$" -s -- sh -c "go run ./"
        depends_on:
            - redis
            - postgres
